"use client";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";

import ChildNav from "./components/childNav";
import { usePathname } from "next/navigation";

const metadata = {
  title: "Next.js App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const pathname = usePathname();
  return (
    <html lang="en">
      <body>
        <Header />

        {pathname.startsWith("/childpage") && <ChildNav />}
        {children}
        <Footer />
        <script
          src="https://kit.fontawesome.com/94a0c02d39.js"
          crossOrigin="anonymous"
          async
        ></script>
      </body>
    </html>
  );
}
